name: Notebooks

on:
  push:
    branches: [ "main", "patch", "feature", "mplot" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    name: Build ubuntu wheel for python${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f examples/requirements.txt ]; then pip install -r examples/requirements.txt; fi
    - name: Test notebook(s)
      run: |
        cd examples
        runpynb get-sleep --sequence
        runpynb readme-examples --sequence
